name: make syntax-status

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check'
        required: true
        default: 'master'

jobs:
  build:

    runs-on: [self-hosted, bastion]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: dummy test
      run: mkdir -p build
    - name: dummy test
      run: touch build/foo
    - name: publish to wiki
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      run: tools/verichecks-to-wiki.sh


