name: make verichecks-status

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check'
        required: true
        default: 'master'

jobs:
  start-veri-checks:
    runs-on: bastion
    steps:
    - name: start-veri-checks
      run: /home/ubuntu/verified-betrfs/tools/aws/start-stop-worker.py --start veri-checks
  build:
    runs-on: veri-checks
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: prep-environment
      run: sudo tools/prep-environment.sh
    - name: install-dafny
      run: tools/install-dafny.sh
    - name: make status
      run: make -j 7 syntax-status
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
    - name: publish to wiki
      uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
      with:
        path: build
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    - name: stop veri-checks
      if: ${{ always() }}
      continue-on-error: true # This step will always fail, since it gets killed when we shutdown
      run: sudo shutdown --poweroff now
