name: make syntax-status

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check'
        required: true
        default: 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: prep-environment
      run: sudo tools/prep-environment.sh
    - name: install-dafny
      run: tools/install-dafny.sh
    - name: make syntax-status
      run: make -j `nproc` syntax-status
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
